# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMesh = channel.unary_unary(
                '/sim.SimulationService/GetMesh',
                request_serializer=simulation__pb2.MeshRequest.SerializeToString,
                response_deserializer=simulation__pb2.MeshResponse.FromString,
                _registered_method=True)
        self.RunAnalysis = channel.unary_unary(
                '/sim.SimulationService/RunAnalysis',
                request_serializer=simulation__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=simulation__pb2.AnalysisResult.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMesh(self, request, context):
        """接口 1: 加载并获取网格数据用于渲染
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAnalysis(self, request, context):
        """接口 2: 执行重心计算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMesh,
                    request_deserializer=simulation__pb2.MeshRequest.FromString,
                    response_serializer=simulation__pb2.MeshResponse.SerializeToString,
            ),
            'RunAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAnalysis,
                    request_deserializer=simulation__pb2.AnalysisRequest.FromString,
                    response_serializer=simulation__pb2.AnalysisResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sim.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sim.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim.SimulationService/GetMesh',
            simulation__pb2.MeshRequest.SerializeToString,
            simulation__pb2.MeshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim.SimulationService/RunAnalysis',
            simulation__pb2.AnalysisRequest.SerializeToString,
            simulation__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
