# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\x03sim\"j\n\x0bMeshRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x16\n\x0eskip_mesh_data\x18\x02 \x01(\x08\x12\x18\n\x10\x64ownsample_ratio\x18\x03 \x01(\x05\x12\x16\n\x0ezero_data_test\x18\x04 \x01(\x08\"B\n\x0cMeshResponse\x12\x10\n\x08vertices\x18\x01 \x03(\x01\x12\x0f\n\x07indices\x18\x02 \x03(\x05\x12\x0f\n\x07normals\x18\x03 \x03(\x02\"\"\n\x0f\x41nalysisRequest\x12\x0f\n\x07\x64\x65nsity\x18\x01 \x01(\x01\"`\n\x0e\x41nalysisResult\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x12\n\ntotal_mass\x18\x04 \x01(\x01\x12\x19\n\x11\x65xecution_time_ms\x18\x05 \x01(\x01\x32}\n\x11SimulationService\x12.\n\x07GetMesh\x12\x10.sim.MeshRequest\x1a\x11.sim.MeshResponse\x12\x38\n\x0bRunAnalysis\x12\x14.sim.AnalysisRequest\x1a\x13.sim.AnalysisResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESHREQUEST']._serialized_start=25
  _globals['_MESHREQUEST']._serialized_end=131
  _globals['_MESHRESPONSE']._serialized_start=133
  _globals['_MESHRESPONSE']._serialized_end=199
  _globals['_ANALYSISREQUEST']._serialized_start=201
  _globals['_ANALYSISREQUEST']._serialized_end=235
  _globals['_ANALYSISRESULT']._serialized_start=237
  _globals['_ANALYSISRESULT']._serialized_end=333
  _globals['_SIMULATIONSERVICE']._serialized_start=335
  _globals['_SIMULATIONSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
